# **Pratham Aggarwal**

![Logo](/assets/img/pp.png)

**University of California, San Diego (UCSD)**  
**Bachelor of Science in Data Science**  
**GPA**: 4.0 | **Provost Honors**  

---

**Theme**: jekyll-theme-minimal

---

### **Downloads**
- [Download Resume](#) <!-- Link to your resume if you want to enable downloads -->

