title: "Pratham Aggarwal"
logo: "/assets/img/pp.png"
# show_downloads: true

education:
  university: "University of California, San Diego (UCSD)"
  degree: "Bachelor of Science in Data Science"
  gpa: "4.0"
  honors: "Provost Honors"

theme: "jekyll-theme-minimal"
